---
title: "Fifth_movies"
format: html
editor: visual
---

##Setup

```{r}
#|label: setup
library(tidyverse)
library(skimr)
library(ggformula)
library(vcd)
library(vcdExtra)
library(vcdExtra)
library(openintro)
library(resampledata)
library(ggalluvial)
```

## Loading Data

```{r}
movies <- read_delim("../Data/movies_modified.csv", delim = ";")
glimpse(movies)
```

## Data Munging

```{r}
movies_modified <- movies %>% 
  mutate(
    movie= as_factor(movie),
    lead_studio= as_factor(lead_studio),
    story= as_factor(story),
    genre= as_factor(genre)) %>% 
  
  mutate(domestic_gross = str_replace(domestic_gross, ",", "."),
         foreign_gross = str_replace(foreign_gross, ",", "."),
         world_gross = str_replace(world_gross, ",", "."),
         budget = str_replace(budget, ",", "."),
         profitability = str_replace(profitability, ",", "."),
         opening_weekend = str_replace(opening_weekend, ",", ".")) %>% 

 mutate(across(where(is.character), as.numeric))

glimpse(movies_modified)

```

## How one thing changes with another

```{r}
movies_modified %>% gf_point(rotten_tomatoes ~ audience_score) %>% gf_lm()
```

```{r}
movies_modified %>% gf_point(profitability ~ budget) %>% gf_lm()
```

```{r}
movies_modified %>% 
  dplyr::filter(profitability <= 20) %>% gf_point(profitability ~ budget) %>% gf_lm() 
  movies_modified %>% 
    dplyr::filter(profitability <= 20) %>%
    gf_point(profitability ~ budget, color = ~genre) %>% 
    gf_lm()
  movies_modified %>% 
    dplyr::filter(profitability <= 20) %>%
    gf_point(profitability ~ budget, color = ~genre) %>% 
    gf_lm() %>% gf_facet_wrap(~ genre)
```

## Propotions

```{r}
Arthritis
```

```{r}
GSS
```

```{r}
HairEyeColor
```

```{r}
email
```

```{r}
vcd::structable(number ~ spam, data=email) %>% 
  addmargins()
```

```{r}
GSS2002
```

```{r}
vcd::structable(Education ~ DeathPenalty, data = GSS2002) %>% 
  addmargins()
vcd::structable(Education ~ DeathPenalty, data = GSS2002) %>%
  vcd::mosaic()
```

##Arthritis mosaic plot

```{r}
arthritis_table <- vcd::structable(Improved ~ Treatment,
                                   data = Arthritis)
arthritis_table
vcd::mosaic(arthritis_table, 
            gp = shading_max, direction = "v",
            main = "Arthritis Treatment Dataset",
labeling = labeling_border(
                varnames = c("F", "F"), # Remove variable name labels
                rot_labels = c(90,0,0,0), #t,r,b,l
                just_labels = c("left", 
                                "left", 
                                "left", 
                                "right"))) # How?
```

```{r}
vcd::mosaic(Improved ~ Treatment, data = Arthritis, 
            direction = "v", gp = shading_max, legend = FALSE)
vcd::mosaic(Improved ~ Treatment, data = Arthritis, 
            type = "expected", direction = "v", gp = shading_max, 
            legend = FALSE)
vcd::assoc(Treatment ~ Improved, # Note formula direction!
           data = Arthritis, 
           gp = shading_max, 
           legend = FALSE) 
```

## Alluvial Plots

```{r}
data(Titanicp, package = "vcdExtra")
Titanicp
```

```{r}
Titanicp %>% ggplot(aes(axis1 = pclass, axis3 = survived, axis2 = sex)) + 
  geom_alluvium(aes(fill = survived), alpha = 0.3) + 
  geom_stratum() + 
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) + scale_x_discrete(limits = c("Class", "Sex", "Survived?")) +
  labs(title = "My Titanic Plot", Subtitle = "Rose is evil", caption = "Made with ggalluvial")
```

```{r}
UCBAdmissions

UCBAdmissions %>% dplyr::as_tibble()

```

```{r}
UCBAdmissions

UCBAdmissions %>% 
  as_tibble() %>% 
  ggplot(aes(axis1 = Dept, axis2 = Gender, axis3 = Admit, y = n)) + 
  geom_alluvium(aes(fill = Admit), alpha = 0.5) + 
  geom_stratum() + 
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) + scale_x_discrete(limits = c("Gender", "Dept")) +
  labs(title = "UCB Admission Frequency Form Data")
```


```{r}
ucb_admit 

ucb_admit%>% 
  ggplot(aes(axis1 = gender, axis2 = dept, axis3 = admit)) +
  geom_alluvium(aes(fill = gender)) +
  geom_stratum(aes(fill = after_stat(stratum))) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Gender, Department, Admitted?")) +
  labs(title = "UCB Admissions Case Form Data")
```


